### PR TITLE
findBestMatch: wrong results for startIndex > 255

### PR DESCRIPTION
**Pull request by aeschli**
findBestMatch returns wrong results for startIndex > 255

### CODE REVIEW

**Comment by NeekSandhu** [comment]
Thank you for fixing that up 🤗!

Will push that in next patch tomorrow

**Comment by NeekSandhu** [comment]
BTW did you have any problems with getting `scripts/build.sh` to work?

**Comment by aeschli** [comment]
It took me a while, but eventually, I got `scripts/build.sh` to work.
I'm on Ubuntu and tried first to use the emscripten apt-get package.
Only after cloning https://github.com/juj/emsdk.git I got things for work.

**Comment by NeekSandhu** [comment]
That's good to know. Just wanted to make to make sure everything's ok.

___

This patch along with #5 are included in `onigasm@2.1.0`. Please npm install again to receive the udpate.

**Pull request merged**
