### PR TITLE
encoding with mapping table

### PR DESCRIPTION
**Pull request by aeschli**

### CODE REVIEW

**Comment by NeekSandhu** [comment]
Looks nice but I hope you are with me on this; We have to beat [`onigasm@2.1`](https://github.com/NeekSandhu/onigasm/commit/0c01c14d62088c59fa36b44fbadf549bcde1c759) in **ALL** the cases of `benchmark.js` before we can proceed with any PR.

Does this beat `2.1`?

*btw thanks for helping out*

**Comment by aeschli** [comment]
benchmark.js from https://github.com/aeschli/onigasm/blob/247b41a63c2010870509fc82bb5c1f6d113c0efa/benchmark.js

Times taken on my machine (running other stuff, so not really scientific)

2.1:
```
Uncached strings < 100 characters
: 77 ms
Cached strings < 100 characters
: 63 ms

Uncached strings < 1000 characters
: 331 ms
Cached strings < 1000 characters
: 287 ms

Uncached strings < 10000 characters
: 3082 ms
Cached strings < 10000 characters
: 2906 ms

Uncached strings < 50000 characters
: 39708 ms
Cached strings < 50000 characters
: 39365 ms

Uncached strings < 100000 characters
: 81807 ms
Cached strings < 100000 characters
: 82741 ms
```

this PR:
```
Uncached strings < 100 characters
: 122 ms
Cached strings < 100 characters
: 11 ms

Uncached strings < 1000 characters
: 374 ms
Cached strings < 1000 characters
: 22 ms

Uncached strings < 10000 characters
: 3356 ms
Cached strings < 10000 characters
: 163 ms

Uncached strings < 50000 characters
: 20628 ms
Cached strings < 50000 characters
: 768 ms

Uncached strings < 100000 characters
: 40431 ms
Cached strings < 100000 characters
: 1540 ms
```

Note that the benchmark should also have some search matches so that the result offsets need to be mapped back..

Changing 'searchTillTheEndButYouWontFindMe to 's' [here](https://github.com/aeschli/onigasm/blob/247b41a63c2010870509fc82bb5c1f6d113c0efa/benchmark.js#L16) results in:
2.1
```
Uncached strings < 100 characters
: 151 ms
Cached strings < 100 characters
: 73 ms

Uncached strings < 1000 characters
: 334 ms
Cached strings < 1000 characters
: 286 ms

Uncached strings < 10000 characters
: 2667 ms
Cached strings < 10000 characters
: 2604 ms

Uncached strings < 50000 characters
: 38143 ms
Cached strings < 50000 characters
: 39847 ms

Uncached strings < 100000 characters
: 86211 ms
Cached strings < 100000 characters
: 85455 ms

```
This PR
```
Uncached strings < 100 characters
: 146 ms
Cached strings < 100 characters
: 33 ms

Uncached strings < 1000 characters
: 481 ms
Cached strings < 1000 characters
: 33 ms

Uncached strings < 10000 characters
: 3646 ms
Cached strings < 10000 characters
: 76 ms

Uncached strings < 50000 characters
: 18920 ms
Cached strings < 50000 characters
: 316 ms

Uncached strings < 100000 characters
: 37562 ms
Cached strings < 100000 characters
: 602 ms
```

**Comment by NeekSandhu** [comment]
Great job on handling cached `OnigString`s but if only we could also make uncached faster than 2.1. Maybe handle those situations conditionally?

**Comment by aeschli** [comment]
I will continue to look into further improvement, but to me, the numbers show a very clear picture. 
Let's not get blocked by 30ms difference for 500 searches, that's really just 0.06ms / search.
Better look at the results for long strings were the current algorithm shows very bad characteristics.

In the second variant of the benchmark, the PR beats all current results. To me, this variant is the far more relevant scenario for tokenizers, as very rarely a tokenizer doesn't find a match. 

Also, let's not forget that another big benefit of the PRs you started (and I tuned) is that we have less code in native and more in JS which will make it much easier to maintain, measure and improve. I'd even be willing to give a few millis per search for that alone. But there's actually no reason that the JS code should be slower given that they all run in the same V8-engine.

**Comment by NeekSandhu** [comment]
Will review it later today :)

**Comment by NeekSandhu** [comment]
Sir, You're a magician. Great work

**Comment by NeekSandhu** [comment]
I had to revert this PR to merge an extended version instead https://github.com/NeekSandhu/onigasm/pull/11

**Pull request merged**
